config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :announcements do
    get "serve", :on => :member
  end
  get 'browse/c_core'
  get 'browse/athletic'
  get 'browse/bell_schedules'
  get 'browse/weather'
  get 'browse/home'
  root 'browse#home'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:serve]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  def serve
    @announcement = Announcement.find(params[:id])
    send_data(@announcement.data, :type => @announcement.mime_type, :filename => "#{@announcement.filename}.jpg", :disposition => "inline")
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        if !params[:picture].blank?
          @announcement.data      = params[:picture].read
          @announcement.filename  = params[:picture].original_filename
          @announcement.mime_type = params[:picture].content_type
          @announcement.save!
        end

        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:text_content, :data, :filename, :mime_type, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  def home
  	@announcements = Announcement.order("created_at DESC")
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement, :html => { :multipart => true, :class => 'form-horizontal'  } do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text_content %><br>
    <%= f.text_field :text_content %>
  </div>
 
  <div class="content">
    <%= file_field_tag :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing Announcements</h1>

<table class="table table-condensed table-striped table-bordered table-clickable">
  <thead>
    <tr>
      <th>Text content</th>
      <th>Data</th>
      <th>Filename</th>
      <th>Mime type</th>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.text_content %></td>
        <td><%= announcement.data %></td>
        <td><%= announcement.filename %></td>
        <td><%= announcement.mime_type %></td>
        <td><%= announcement.user_id %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Delete', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path, :class => "btn btn-success" %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text content:</strong>
  <%= @announcement.text_content %>
</p>

<p>
  <strong>Data:</strong>
  <%= @announcement.data %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @announcement.filename %>
</p>

<p>
  <strong>Mime type:</strong>
  <%= @announcement.mime_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @announcement.user_id %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/browse/c_core.html.erb
<table class="mediumWrap" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td class="topLeft"></td>
            <td class="topMiddle"><em><span style="font-size: 116%;"><strong>Common Core/Essential Standards</strong></span></em></td>
            <td class="topRight"></td>
        </tr>
        <tr>
            <td class="leftMiddle"></td>
            <td class="tableTemplateContent"><!-- content area -->              
        <br>
            The Common Core State Standards provide a consistent, clear  understanding of what students are expected to learn, so teachers and  parents know what they need to do to help them. The standards are  designed to be robust and relevant to the real world, reflecting the  knowledge and skills that our young people need for success in college  and careers. With American students fully prepared for the future, our  communities will be best positioned to compete successfully in the  global economy.<br>
            <em>Taken from http://www.corestandards.org/</em><hr>
            Unpacking has been created to be a support tool for the implementation of the Essential Standards.&nbsp; The document, linked to the right, was made to help ensure educators understand the new standards so they may increase student achievement.&nbsp; <hr>
            The Crosswalks docucment, linked to the right, compares the current standard course of study to the newly adopted standards.&nbsp; While not intended to answer all questions, it will aid schools and teachers on internalizing and planning to teach the new standards.<hr>
            </td>
            <!--end tableTemplateContent-->
            <td class="rightMiddle"></td>
        </tr>
        <tr>
            <td class="bottomLeft"></td>
            <td class="bottomMiddle"></td>
            <td class="bottomRight"></td>
        </tr>
    </tbody>
</table>

app/views/browse/home.html.erb
<% @announcements.each do |announcement| %>

	<% if announcement.data.nil? or announcement.data == "" %>
	<div class="panel panel-default">
	  <div class="panel-body">
	    <%= announcement.text_content %>
	    <hr/>
	    <p><%= announcement.created_at.to_easy_time %></p>
	  </div>
	</div>
	<% else %>
	<div class="panel panel-default">
	  <div class="panel-body">
	    <%= image_tag serve_announcement_path(announcement.id), :style => "height: 150px;" %>
	    <hr/>
	    <p><%= announcement.created_at.to_easy_time %></p>
	  </div>
	</div>
	<% end %>
<% end %>

app/views/browse/weather.html.erb
<center><h3>Inclement Weather Information</h3></center>


<p>There will be times when weather conditions require schools to be closed, the opening of school delayed, or schools to be closed early due to weather/hazardous driving conditions.  The following information is provided as to the process/procedures that we will follow:</p>


<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#tv" role="tab" data-toggle="tab">Contact</a></li>
  <li><a href="#studentsandstaff" role="tab" data-toggle="tab">Students And Staff</a></li>
  <li><a href="#Workdays" role="tab" data-toggle="tab">Optional Teacher Workdays</a></li>
  <li><a href="#delays" role="tab" data-toggle="tab">Delays</a></li>
  <li><a href="#afterschool" role="tab" data-toggle="tab">After School</a></li>
  <li><a href="#makeup" role="tab" data-toggle="tab">Make Up Days</a></li>
  <li><a href="#earlydismissal" role="tab" data-toggle="tab">Early Dismissal</a></li>
  <li><a href="#more" role="tab" data-toggle="tab">More</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="tv">
    <br/>
    <p>Decisions regarding the closing or delayed opening of school will be made by 6:00 a.m. if at all possible.  The decision will be communicated via Connect Ed as well as the following radio and TV stations and announced by 6:15 a.m.  Information will also be posted at our website, Facebook and Twitter accounts. Dr. Little also announces via his Twitter account. If no announcement is made school will operate on a normal schedule.</p>

    <h5> TV - CABLE </h5>
    <p> 11   WXII TV Winston-Salem
    8    WGHP High Point
    2    WFMY Greensboro
    10   WXLV Winston-Salem</p>


    <h5> RADIO </h5>
    <p> WSYD   Mount Airy 1300 AM  
    WFDD   Winston Salem 88.5 FM
    WPAQ   Mount Airy   740 AM
    WTQR   Winston Salem 104.1 FM </p>
  </div>

  <div class="tab-pane" id="studentsandstaff">
    <br/>
    <p>If school is closed for students and staff, no school based 10-month employees will report to work, 12-month office staff will report to work as soon as travel is safe.  If they are unable to report to work, they will use annual leave/vacation day.</p>
  </div>


  <div class="tab-pane" id="Workdays">
    <br/>
    <p>If school is closed with an optional teacher workday, 10-month employees will report to work at their discretion.   If any employee chooses not to work on an optional day they will use appropriate leave time. </p>
  </div>

  <div class="tab-pane" id="delays">
    <br/>
    <p>If school is delayed all schedules will be delayed the designated amount of time including buses, staff reporting times, student reporting time.  Principals will be responsible for their respective building during the delay. </p>

    <p>Parents are encouraged to have arrangements in place in case of a closing, delay, or early dismissal. </p>
  </div>


  <div class="tab-pane" id="afterschool">
    <br/>
    <p>After school programs will follow the same schedule as announced for the schools. </p>
  </div>


  <div class="tab-pane" id="makeup">
    <br/>
    <p>Make up days for days missed due to inclement weather will follow the make up schedule on the school calendar. </p>
  </div>

  <div class="tab-pane" id="earlydismissal">
    <br/>
    <p>Early dismissal due to inclement weather may be necessary on occasion.  Every effort will be made to make this decision at least an hour before the dismissal. </p>
  </div>

  <div class="tab-pane" id="more">
    <br/>

    <h5> More Information..... </h5>
    <h5> How is a Decision Made and Who Makes the Call? </h5>

    <h5> What factors do we look at in determining to close school? </h5>

    <p> Several factors are considered.  The  most important factor we consider when making this decision is the safety of our students and staff. One of the first factors we take into account are the current conditions.  Is frozen precipitation (snow, sleet, freezing rain) falling?  If so, what is the temperature?  We don't want to start a bus route if frozen precipitation is falling and the temperatures are close to or below freezing.  If no precipitation is currently falling the next factor would be road conditions.  Are the roads too dangerous for travel?  Are there spots or areas that present a hazard to bus and car traffic?  If so, we will not jeopardize the safety of our students and staff members.  We also consider the time of the event.  Will the timing of the event allow us to start school on a two hour delay and allow us to have school and get students and staff home safely? We consider several of these same factors if weather changes after we are already at school.</p> 

    <h5> Do we take forecasts into account? To what extent? What services do we trust for weather news? </h5>

    <p> We consider every piece of information we can gather.  We monitor weather forecasts and the movement of weather systems via the internet, email forecasts, television, and we also speak directly with representatives with the National Weather Service on occasion.  We monitor forecasts and radar from local, state, and national weather centers.  If it appears as if significant winter weather is on the way and we can be proactive and communicate with our students, staff, and parents ahead of time, we do so.  For example, there have been occasions where weather forecasts have indicated a high probability of an impending event and we have decided to delay or close school.  Safety is our number one priority. </p>

    <h5> What process is involved (does someone ride the roads, etc.)? </h5>

    <p> Ultimately, the decision to cancel or delay school rests with the superintendent.  Typically, the decision is made based upon information collected by several people and from several sources.  We have a team of 3 individuals who ride the roads in our system to determine if it is safe to travel to and from school, Bryan Taylor, Larry Davis, and Dr. Little hit the streets on a days where a hazardous weather event is taking place or predicted; they begin routes between 4:00 and 4:30 a.m.  Once the roads have been checked the team meets at the central office at 5:15 to discuss the weather and road conditions in preparation for a decision.  We may also communicate with the city police department, NCDOT, and the NC Highway Patrol regarding road conditions.  Whenever possible, we try to make a decision before 6:00 a.m.  Our first bus routes begin between 6:30 and 6:40 a.m. and a decision must be made prior to beginning bus routes if possible.  Once the decision to close or delay is made, we begin notifying the various media (television, radio, etc.) of our decision.  We also send out a message via our telephone message system (Connect-Ed) to every student's and staff member's contact number. </p>

    <h5> Does being part of the county transportation department shape our decision? </h5>

    <p> Being a part of the county transportation system does not factor into our decision making process.  The county transportation department primarily provides mechanical support of the yellow bus fleet.  They do not make the closing or delay decision for the Mount Airy City Schools, but we do share information.  Superintendents in neighboring school districts often discuss road conditions as we determine what will be the best decision for the day. </p>

    <h5> How is it decided to have delayed opening as opposed to closing all together? </h5>

    <p>We are required to attend school 180 days, therefore, when possible we would prefer to delay instead of close school.  For example, we will consider whether or not the roads will become safer once the sun is up and melting can take place.  Is the temperature expected to rise above freezing as the morning progresses?  However, while a two hour delay will push the start time for students two hours later, buses will begin running routes at roughly 8:15 a.m. instead of 6:15 a.m.  If we call for a two hour delay, there may be times when conditions do not improve and we could then close school, so parents should stay tuned on those mornings.  Again, safety is our number one priority. </p>

    <h5> How do we decide to close early? </h5>

    <p>We begin by monitoring forecasts and conditions.  We ask ourselves several questions: Is bad weather in the area or on the way?  One of the first things we do is tell our bus drivers to be on stand by in the event we have to close school early.  We also have to consider the size and timing of the event.  Will temperatures remain above freezing?  If so, would it be safer to remain at school?  Once a decision to close early is made we begin contacting the schools and bus drivers.  We then contact all media outlets and send out a Connect Ed message (our automated telephone calling system). </p>

    <h5> Summary </h5>
    <p> This is one of the most significant decisions our team makes.  Ultimately, the safety of more than 2000 people (students and staff) is at stake.  Every time a decision about closing or delaying school is made, we recognize not everyone will be happy.  Changing school schedules is inconvenient for everyone, but we will always err on the side of safety for students and staff.  Those big yellow buses are the safest transportation on the road, but we also have staff and students driving smaller vehicles.  Parents entrust us with their most precious assets, their children.  We want parents to know that we are most concerned about what is safest for children and our staff, not what might be inconvenient. </p>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MAHS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MAHS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/browse/weather">Weather</a></li>
        <li><a href="http://mail.google.com/a/mtairy.k12.nc.us">Staff Email</a></li>
        <li><a href="https://mtairy.powerschool.com/teachers/pw.html" target="_blank">PowerTeacher</a></li>
        <li><a href="https://mtairy.powerschool.com/admin/pw.html" target="_blank">PowerSchool Admin</a></li>

		<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Students <span class="caret"></span></a>
	    <ul class="dropdown-menu" role="menu">
	      <li><a href="/browse/bell_schedules">Bells Schedule</a></li>
	      <li><a href="#">Clubs</a></li>
	      <li><a href="#">Dress Code</a></li>
	      <li><a href="#">Dress Code Memo From MAHS</a></li>
	      <li><a href="#">Drivers &amp; Traffic</a></li>
	      <li><a href="#">eLearning NC</a></li>
	      <li><a href="#">F4K/Crusing</a></li>
	      <li><a href="#">Honor Code &amp; Cheating Policy</a></li>
	      <li><a href="#">Naviance-Family Connection</a></li>
	      <li><a href="#">NC Graduation Requirements</a></li>
	      <li><a href="#">Supply List for All Courses</a></li>
	      <li><a href="#">Student Automobiles Policy</a></li>
	      <li><a href="#">Stu Usernames / Passwords</a></li>
	  	</ul>
     </li>

		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Parents <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="http://macs.schoolfusion.us/modules/cms/pages.phtml?pageid=161795&sessionid=67fe2336c92e719e2c02530555053390&t=78fe120cc2f44eedba403d87a2c65b79&sessionid=67fe2336c92e719e2c02530555053390&t=78fe120cc2f44eedba403d87a2c65b79">Athletic Physical Forms</a></li>
            <li><a href="#">AIG Plans</a></li>
            <li><a href="#">Attendance Policy - MACS</a></li>
            <li><a href="#">Attendance / Tardy Procedures - MACS</a></li>
            <li><a href="#">Discipline Policy</a></li>
            <li><a href="#">Dress Code Memo from MAHS</a></li>
            <li><a href="#">Family Resource Center</a></li>
            <li><a href="#">Graduation Requirements</a></li>
            <li><a href="#">Lunch Pre-pay</a></li>
            <li><a href="#">MAHS Grading Practicies</a></li>
            <li><a href="#">PTO</a></li>
            <li><a href="#">Parent Registration</a></li>
            <li><a href="#">Powerschool Parent</a></li>
          </ul>
        </li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Staff <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><a href="/browse/c_core">C Core / Essential Standards</a></li>

        <li><a href="#">Staff Directory</a></li>
        <li><a href="#">SchoolFusion Grades</a></li>
        <li><a href="#">Technology Repair Request</a></li>
        <li><a href="#">MAHS Staff Handbook (Condensed)</a></li>
      </ul>
    </li>

    <li><a href="#">Class Pages</a></li>
    <li><a href="http://macs.schoolfusion.us/?sessionid=bbebb53ab67e1088f2ebcec5799e874b&amp;t">District Home</a></li>
    <% if current_user.nil? %>
      <li><a href="/announcements">Sign In</a></li>
    <% else %>
      <li><a href="/logout">Sign Out</a></li>
      <li><a href="/announcements">Announcements</a></li>
    <% end %>
  </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container super_container body">
<%= yield %>

<footer class='footer'>
  <hr />
  <% if Time.now.year == 2014 %>
  	&copy; 2014 Elijah Ray Smith</a>
  <% else %>
  	&copy; 2014-<%= Time.now.year %> Elijah Ray Smith</a>
  <% end %>

</footer>

</div>


</body>
</html>